### ISSUE TITLE
Great minds and all that ..

### ISSUE THREAD

**Issue by Road-block** [skyler-code/ReforgeLite#1]
I was going to wait for next build before trying to find a workaround for the itemstring missing reforgeid 😃 

Anyway, can probably abandon the project now 😝 

https://github.com/Road-block/ReforgeLiteClassic

**Comment by skyler-code** [comment]
Haha yeah I've been waiting around the last few weeks of beta for somebody else to do it but was getting antsy with just a few weeks to go before prepatch. So I finally decided to look into it on my own, noticed it would need a workaround with reforgeid not implemented, and realized why nobody had touched it yet. I'm sure they'll implement it soon and render a lot of my work useless, but with the sheer amount of bugs still on beta...I decided not to wait around
