### ISSUE TITLE
"at least melee hit cap" goes below hitcap

### ISSUE THREAD

**Issue by wlfbck** [skyler-code/ReforgeLite#10]
I think this might be a result of #6 
I don't think it matters, but i'm a frost DK, meaning i get 3% hit from talents.
If i put the statweight for hit and expertise to 0, the calculation will put me under the hitcap, despite the rule being active:
![image](https://github.com/skyler-code/ReforgeLite/assets/1621804/1fafdfb4-2933-4be6-86de-248d380a6a6f)

But if put any weight to expertise (not hit!), it works out fine.

**Comment by skyler-code** [comment]
It's not really a rule in that sense. The only rule is giving you the highest score, so you need to give hit some value in the first place.

**Comment by wlfbck** [comment]
Aah, i see. Me and my guildies were under the impression that it's a minimum. Since you usually want that to kick reliably.

**Comment by skyler-code** [comment]
It'll behave that way if you give hit a value above haste. So like 5, for example. That would make the addon try to get you as close as hit cap without going under
![image](https://github.com/skyler-code/ReforgeLite/assets/23067226/5979dc5f-f2a1-464a-8a15-16a6f915d24d)
