### ISSUE TITLE
Items do not take into account gems and enchants

### ISSUE THREAD

**Issue by rainecheck** [skyler-code/ReforgeLite#12]
See attachments - addon isn't taking into account any sources of hit or expertise rating from gems and enchants (and thus probably other stats).

![image](https://github.com/skyler-code/ReforgeLite/assets/33798530/53cbb809-5eb1-465f-af0c-1083aa6328b6)

![image](https://github.com/skyler-code/ReforgeLite/assets/33798530/607a5e14-ec31-4535-be5a-ddd115a98785)

**Comment by skyler-code** [comment]
Gems/enchants are baked into your character's stats
For example with mastery, the addon runs `GetCombatRating(CR_MASTERY)`
![image](https://github.com/skyler-code/ReforgeLite/assets/23067226/5657e15e-f48b-4ede-849a-00e6292b38d4)
![image](https://github.com/skyler-code/ReforgeLite/assets/23067226/980a474e-53f9-468e-9199-b4df04bf8ed6)

These boots give me 159+20 = 179 mastery. 1973 - 179 = 1794
