### ISSUE TITLE
Breaking Raid Frames

### ISSUE THREAD

**Issue by timothyrichards** [skyler-code/ReforgeLite#17]
Hey, not sure what would really be causing this to be completely honest but I have reproducible steps and some errors to work with.

This issue might be related to issue https://github.com/skyler-code/ReforgeLite/issues/13

While working on my own addons I had this same bug when I overwrote a default blizzard UI functions with a new value, in my case I was doing something like: ```PlayerFrame.SetPoint = function() end```

I've tested this with all addons disabled except for ReforgeLite and BugSack + BugGrabber.

Whenever I'm in combat and in a group, if anyone leaves, joins, or a pet is summoned, or dies, I get a lua error:
```1x [ADDON_ACTION_BLOCKED] AddOn 'ReforgeLite' tried to call the protected function 'CompactRaidFrame1:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_FrameXMLBase/FlowContainer.lua"]:176: in function `FlowContainer_DoLayout'
[string "@Blizzard_FrameXMLBase/FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:62: in function `CompactRaidFrameContainer_OnEvent'
[string "*Blizzard_CompactRaidFrameContainer.xml:79_OnEvent"]:1: in function <[string "*Blizzard_CompactRaidFrameContainer.xml:79_..."]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
```

If you try to target the specific unit causing the error, it will also show this popup:
![image](https://github.com/skyler-code/ReforgeLite/assets/59814951/afd42046-84ec-4c0d-93a0-8af74812c125)

Steps to reproduce:
- Open group finder and create a custom party
- Enter combat with a target dummy
- Summon a pet while in combat or invite another player to the group

In my case I was on a shadow priest and summoned a Shadowfiend.

If the information is helpful, here are the settings I'm using for my raid frames profile:
![image](https://github.com/skyler-code/ReforgeLite/assets/59814951/4194d5b3-14b8-46b1-8e4a-ced48c7e3fa9)
![image](https://github.com/skyler-code/ReforgeLite/assets/59814951/ca987331-d2e1-436a-8289-0dc8751e41e6)

If you need any more information from me I'd be happy to help provide that information!

**Comment by skyler-code** [comment]
Should be fixed now with the latest release. Let me know if you run into any issues
