### ISSUE TITLE
Interface/AddOns/ReforgeLite/ReforgeLite.lua:1752: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by xmcdizzle** [skyler-code/ReforgeLite#2]
Hello, trying to play around with this continued version of ReforgeLite, and I'm running into this LUA error whenever going to the Reforge NPC or with attempting to open /reforge

Pulled latest version from curse, v1.1.2
----------------------------------------------------------------------------------------------------------

Message: Interface/AddOns/ReforgeLite/ReforgeLite.lua:1752: attempt to perform arithmetic on a nil value
Time: Sat Apr 20 21:36:32 2024
Count: 1
Stack: Interface/AddOns/ReforgeLite/ReforgeLite.lua:1752: attempt to perform arithmetic on a nil value
[string "@Interface/AddOns/ReforgeLite/ReforgeLite.lua"]:1752: in function <Interface/AddOns/ReforgeLite/ReforgeLite.lua:1740>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ReforgeLite/ReforgeLite.lua"]:1776: in function <Interface/AddOns/ReforgeLite/ReforgeLite.lua:1775>
[string "@Interface/AddOns/ReforgeLite/ReforgeLite.lua"]:1787: in function `GetReforgeID'
[string "@Interface/AddOns/ReforgeLite/ReforgeLite.lua"]:1808: in function `UpdateItems'
[string "@Interface/AddOns/ReforgeLite/ReforgeLite.lua"]:2260: in function `OnEvent'
[string "@Interface/AddOns/ReforgeLite/ReforgeLite.lua"]:2315: in function <Interface/AddOns/ReforgeLite/ReforgeLite.lua:2315>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: tip = ReforgeLiteTooltip {
 SetBorderBlendMode = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:309
 NineSlice = Frame {
 }
 0 = <userdata>
 updateTooltip = 0.200000
 TooltipBackdropOnLoad = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:278
 TopOverlay = Texture {
 }
 GetBackdropColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:297
 GetBackdropBorderColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:305
 needsReset = true
 BottomOverlay = Texture {
 }
 SetBackdropColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:293
 layoutType = "TooltipDefaultLayout"
 SetBackdropBorderColor = <function> defined @Interface/AddOns/Blizzard_SharedXML/SharedTooltipTemplates.lua:301
}
_ = "Armbands of the Ashen Saint"
item = "[Armbands of the Ashen Saint]"
existingStats = <table> {
 ITEM_MOD_INTELLECT_SHORT = 77
 ITEM_MOD_SPIRIT_SHORT = 57
 ITEM_MOD_STAMINA_SHORT = 122
 EMPTY_SOCKET_BLUE = 1
 ITEM_MOD_HASTE_RATING = 49
}
srcStat = 1
destStat = nil
(for index) = 10
(for limit) = 17
(for step) = 1
i = 10
tipName = "ReforgeLiteTooltipText%s10"
leftText = "+10 Intellect and +10 Spirit"
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
}
(for control) = 1
statId = 1
statInfo = <table> {
 long = "Spirit"
 tip = "Spirit"
 name = "ITEM_MOD_SPIRIT_SHORT"
 mgetter = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:262
 parser = "+(.+) Spirit"
 getter = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:259
}
statValue = "10 Intellect and +10"
(*temporary) = 57
(*temporary) = nil
(*temporary) = "10 Intellect and +10"
(*temporary) = nil
(*temporary) = "(.+)"
(*temporary) = "attempt to perform arithmetic on a nil value"
GetReforgeTableIndex = <function> defined @Interface/AddOns/ReforgeLite/ReforgeLite.lua:1731

**Comment by skyler-code** [comment]
Thank you for the report!

**Comment by xmcdizzle** [comment]
For sure! Appreciate the work you are putting in on this. I know many will be happy, cheers
