### ISSUE TITLE
Druid forcing tanking model all specs

### ISSUE THREAD

**Issue by Aetherentity** [skyler-code/ReforgeLite#20]
Druid reforging doesn't have the option to set caps in any spec, appears to be forcing the tanking model regardless of spec.

![image](https://github.com/skyler-code/ReforgeLite/assets/173319382/e19d17df-b563-4028-b950-f50b461f7baa)

above SS using balance preset but addon is forcing tanking model.

**Comment by skyler-code** [comment]
Fixed with https://github.com/skyler-code/ReforgeLite/commit/668227d46fdf46e5d58a37686a6fc6bee17baa12
