### ISSUE TITLE
Show reforged stats doesn't work with Mastery on v1.6.1

### ISSUE THREAD

**Issue by Kolmarwow** [skyler-code/ReforgeLite#21]
ReforgeLite v1.6.1 seems to have broken the "Show reforged stats in item tooltips" setting. If you mouseover an item that you've reforged from say Expertise to Crit then it works fine and shows "Reforged (Expertise > Crit)" but if an item has been reforged from Mastery to another stat then it just shows "Reforged".

This was tested on a lvl 85 arms warrior with all other addons disabled.

**Comment by skyler-code** [comment]
fixed with https://github.com/skyler-code/ReforgeLite/commit/af879f2e139ffc84c64376b358f0f17b5f7fd87b
