### ISSUE TITLE
Enhancement Shaman Spirit issue

### ISSUE THREAD

**Issue by GeorgeFotopoulos** [skyler-code/ReforgeLite#25]
Hello, I would like to point out that when I try to reforge the equipment of my Shaman on his Enhancement spec, the AddOn for some reason reforges many of my items to Spirit. I have noticed that this happens if the speed slider is set to the leftmost value. If I move it towards the right, then regardless of where I put the slider, the AddOn will no longer reforge to Spirit.

**Comment by skyler-code** [comment]
Fixed with v1.9.0
