### ISSUE TITLE
Addon causes lag spikes if you switch equipment after calculating

### ISSUE THREAD

**Issue by Kolmarwow** [skyler-code/ReforgeLite#26]
If you press the "Calculate" button a few times and then try switching any gear around it'll cause a ~1 sec lag spike, especially noticeable when you switch whole equipment sets. When you /reload then the issue is gone until you do more calculations, this was tested with all addons disabled except ReforgeLite. 
I downgraded to narrow down when this happened and this behavior was introduced in v1.7.0, before that it was fine.

**Comment by skyler-code** [comment]
Updates are now dramatically throttled with v1.7.2. If you swap sets back and forth, it'll still eat up memory but it shouldn't be as extreme now.
