### ISSUE TITLE
[Request] Color reforge'd stat lines in tooltip 

### ISSUE THREAD

**Issue by orionshock** [skyler-code/ReforgeLite#35]
I'd like to ask for a way to color the stat lines on the tooltip for the stat that was reforged away to the new stat.
Something like: 
![image](https://github.com/user-attachments/assets/42d3d0fa-bcb4-4f4b-a7c0-72eb5b21acdb)

I've made an addon stub myself that does this already - but as ReforgeLite is already scanning through the tooltip, it could also color the line too...

**Comment by skyler-code** [comment]
Great idea! Thank you!
