### ISSUE TITLE
Over hit cap after newest version? 

### ISSUE THREAD

**Issue by Schmalan** [skyler-code/ReforgeLite#6]
Might be wrong in settings but since the new update I noticed I am over hit cap when using ReforgeLite. Downloaded 1.3 and im at 18.6% spell hit under the Ele Shaman Preset redownloaded 1.2.7 and changed no settings between the two and got 17%. Any help would be awesome ty and thanks for the great addon!

**Comment by skyler-code** [comment]
Could you try the latest version 1.4 and tell me if anything changed for you?

**Comment by Schmalan** [comment]
Looks like it is good for me now. I updated from 1.2.7 to 1.4 went to reforge and nothing changed so that is good 17% hit.

**Comment by Schmalan** [comment]
It seems to be working for Ele Shaman but a buddy of mine is having issues with Arms Warrior going to 13% hit with the newest 1.4 . the settings are set to 961 and everything is the way it should it just over caps him.
