### ISSUE TITLE
Lua error won't reforge at all

### ISSUE THREAD

**Issue by seakoria** [skyler-code/ReforgeLite#7]
2x ReforgeLite/ReforgeEngine.lua:687: script ran too long
[string "@ReforgeLite/ReforgeEngine.lua"]:687: in function `?'
[string "@ReforgeLite/ReforgeEngine.lua"]:965: in function <ReforgeLite/ReforgeEngine.lua:954>
[string "=(tail call)"]: ?
[string "@ReforgeLite/ReforgeLite.lua"]:1388: in function <ReforgeLite/ReforgeLite.lua:1387>

Locals:
self = Frame {
 BottomLeftCorner = Texture {
 }
 itemTable = Frame {
 }
 GetMeleeHitBonus = <function> defined @ReforgeLite/Presets.lua:50
 IsReforgeMatching = <function> defined @ReforgeLite/ReforgeLite.lua:2143
 InitPresets = <function> defined @ReforgeLite/Presets.lua:883
 GetCapScore = <function> defined @ReforgeLite/ReforgeLite.lua:425
 CapAllows = <function> defined @ReforgeLite/ReforgeEngine.lua:276
 ChooseReforgeClassic = <function> defined @ReforgeLite/ReforgeEngine.lua:507
 dbkey = "裁縫倉庫 - 古雷曼格"
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 GetNeededSpellHit = <function> defined @ReforgeLite/Presets.lua:71
 UpgradeDB = <function> defined @ReforgeLite/ReforgeLite.lua:139
 methodReset = ReforgeLiteMethodResetButton {
 }
 ADDON_LOADED = <function> defined @ReforgeLite/ReforgeLite.lua:2367
 ComputeReforgeCore = <function> defined @ReforgeLite/ReforgeEngine.lua:923
 debugButton = ReforgeLiteDebugButton {
 }
 db = <table> {
 }
 OnTooltipSetItem = <function> defined @ReforgeLite/ReforgeLite.lua:2296
 tankingStats = <table> {
 }
 deletePresetButton = ReforgeLiteDeletePresetButton {
 }
 TopEdge = Texture {
 }
 statWeightsCategory = Frame {
 }
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 GetNeededMeleeHit = <function> defined @ReforgeLite/Presets.lua:63
 UpdateMethodCategory = <function> defined @ReforgeLite/ReforgeLite.lua:1572
 pawnButton = ReforgeLiteDeletePresetButton {
 }
 OnCommand = <function> defined @ReforgeLite/ReforgeLite.lua:2394
 presetMenu = ReforgeLitePresetMenu {
 }
 GetMethodScore = <function> defined @ReforgeLite/ReforgeEngine.lua:79
 targetLevelText = FontString {
 }
 CreateFrame = <function> defined @ReforgeLite/ReforgeLite.lua:729
 SetTankingModel = <function> defined @ReforgeLite/ReforgeLite.lua:1061
 SetAnchor = <function> defined @ReforgeLite/ReforgeLite.lua:618
 IsItemLocked = <function> defined @ReforgeLite/ReforgeEngine.lua:287
 pdb = <table> {
 }
 itemSlots = <table> {
 }
 methodOverride = <table> {
 }
 statWeights = Frame {
 }
 STATS = <table> {
 }
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
 ParsePawnString = <function> defined @ReforgeLite/ReforgeLite.lua:450
 UpdateMethodStats = <function> defined @ReforgeLite/ReforgeEngine.lua:184
 methodStats = Frame {
 }
 SetStatWeights = <function> defined @ReforgeLite/ReforgeLite.lua:1069
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 scrollBarShown = true
 RemoveCapPoint = <function> defined @ReforgeLite/ReforgeLite.lua:1011
 GetExpertiseBonus = <function> defined @ReforgeLite/Presets.lua:56
 MakeReforgeOption = <function> defined @ReforgeLite/ReforgeEngine.lua:297
 UpdateBuffs = <function> defined @ReforgeLite/ReforgeLite.lua:1200
 settingsCategory = Frame {
 }
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 UpdateContentSize = <function> defined @ReforgeLite/ReforgeLite.lua:1779
 capPresets = <table> {
 }
 close = Button {
 }
 CreateOptionList = <function> defined @ReforgeLite/ReforgeLite.lua:1233
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 GetReforgeIDFromString = <function> defined @ReforgeLite/ReforgeLite.lua:1858
 DiminishStat = <function> defined @ReforgeLite/ReforgeEngine.lua:76
 UpdateCapPreset = <function> defined @ReforgeLite/ReforgeLite.lua:1035
 UpdateStatWeightList = <function> defined @Int

**Comment by rainecheck** [comment]
Looks like this occurs when the Speed bar is set to the minimum value. It can be bypassed by putting it up slightly.

**Comment by skyler-code** [comment]
Fixed with v1.9
